### ISSUE TITLE
Пропадают ссылки

### ISSUE THREAD

**Issue by zaeboba** [Lifailon/LibreKinopoisk#1]
Адблоки отключал, все равно пропадает, вот пример:
[msedge_17.37.17.webm](https://github.com/user-attachments/assets/2846fd82-0d11-40f5-a464-1d12fd9468ce)

**Comment by Lifailon** [comment]
> Адблоки отключал, все равно пропадает, вот пример:
> [msedge_17.37.17.webm](https://github.com/user-attachments/assets/2846fd82-0d11-40f5-a464-1d12fd9468ce)
> 

Такое поведение указывает на работу блокировщика. Иногда после отключения блокировщика для сайта, может потребоваться переустановка самого расширения.

Если не поможет, попробуйте удалить AdBlock (особенно актуально, если давно не обновляли его), проверьте, что расширение работает, и потом установить обратно, отключив его для домена kinopoisk.ru.

Если после удаления не заработает расширение, то в системе присутствует другой блокировщик, возможно потребуется переустановка браузера.

Дайте обратную связь по результатам.

**Comment by zaeboba** [comment]
какой ты радикальный.. целый браузер переустанавливать.
а 



просто скрипт сделать нельзя? тип такого - https://github.com/Kirlovon/Tape-Operator (на юблоки пофиг, работает)
чтоб можно было и в другом браузере пользоваться, а не только в чморехром

но то что я в ссылке привел фигня, у него и половины нет того что в твоем 
https://github.com/user-attachments/assets/b541f552-63f4-4aab-9d7a-feee4612cc00

**Comment by Lifailon** [comment]
> какой ты радикальный.. целый браузер переустанавливать. а
> 
Попробуйте начать с переустановки этого расширения, и если не поможет, тогда AdBlock. Переустановка браузера, это крайняя мера. В случае, если в системе или браузере присутствует другой блокировщик, его нужно вычленить и отключить для сайта.

> просто скрипт сделать нельзя? тип такого - https://github.com/Kirlovon/Tape-Operator (на юблоки пофиг, работает) чтоб можно было и в другом браузере пользоваться, а не только в чморехром
>
Это в первую очередь расширение для браузера Google Chrome, возможно в будущем добавлю поддержку других браузеров. Скрипт или развертывание сайта - это уже архитектурно другой подход, у расширение основная функция и отличительная особенность - это фронт для TorAPI, который ещё в разработке.

**Comment by zaeboba** [comment]
переустановка расширения.
жесть.
